### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by gridworkz** [sashabaranov/pike#1]
When running: `pike osboxes.yaml` I get the following error: 

```
Project directory must not exist. Try rm -r /home/osboxes/go/src
```

I've attached the yaml file I'm trying to Pike. Cheers, Dave

[osboxes.zip](https://github.com/sashabaranov/pike/files/5470025/osboxes.zip)

**Comment by sashabaranov** [comment]
@gridworkz Hey, this format is not compatible with pike. Check out an example: https://github.com/sashabaranov/pike/blob/master/examples/animals.yaml
